name: Docker CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: docker build -t ghcr.io/kostya05a/python-deploy:1.0 .
    - run: docker push ghcr.io/kostya05a/python-deploy:1.0
    
    - name: run ssh
      run: ssh -o "StrictHostKeyChecking no" 'kostya05a-123-3xh9f5udsm2#g3jMWQAq2dDgU0dsi.VjFFuQyjetmBlB@kostya05a-123-3xh9f5udsm2.ssh.ws-eu106.gitpod.io' 'cd /workspace/123 && docker compose pull && docker compose up -d'
